### ISSUE TITLE
Kanban board Setup

### ISSUE THREAD

**Issue by Emmanuelaaron** [Emmanuelaaron/spaceships#25]
This is the [link](https://github.com/Emmanuelaaron/spaceships/projects/1) to our kanban project.
We are a team of three people.

**Comment by helman101** [comment]
# STATUS: APPROVED 🟢 🥳 

Hi @Emmanuelaaron, @enionsouza and @mariordgez    🥇 , 

### Congratulations!!! 🥳 🎉

You have successfully completed all the expectations for this project, there is nothing more to do here, now you can go on your way and keep improving your skills.

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
